# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build :
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Python setup
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyInstaller
    - name: Unittest testing
      run: |
        python test.py
    - name: Executable compilation
      run: |
        pyinstaller --onefile calculator.py
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          dist
          !dist/**/*.md
